--- #YAML:1.0
name:                Acme-MetaSyntactic-RefactorCode
version:             0.04
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Acme::MetaSyntactic:           0
    B::Deobfuscate:                0.14
    B::Keywords:                   0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
