--- #YAML:1.0
name: Acme-MetaSyntactic-RefactorCode
version: 0.01
author:
  - Jerome Fenal <jfenal@free.fr>
abstract: The great new Acme::MetaSyntactic::RefactorCode!
license: perl
requires:
  Test::More: 0
provides:
  Acme::MetaSyntactic::RefactorCode:
    file: lib/Acme/MetaSyntactic/RefactorCode.pm
    version: 0.01
generated_by: Module::Build version 0.2608
